---
# tasks file for franz

- block:
    - name: Get latest release of Franz
      uri:
        url: https://api.github.com/repos/meetfranz/franz/releases/latest
      register: r_franz_latest_release

    - name: Set franz_version to latest release
      set_fact:
        franz_version: "{{ r_franz_latest_release.json.tag_name }}"
  when: franz_version == 'latest'

- name: Create Franz install directory
  file:
    path: "{{ franz_install_dir }}"
    state: directory
    mode: 0755

- name: Download Franz
  get_url:
    url: https://github.com/meetfranz/franz/releases/download/{{ franz_version }}/{{ franz_appimage_filename }}
    dest: "{{ franz_install_dir }}/Franz.AppImage"
    mode: 0755

- name: Create Franz icon directory
  file:
    path: "{{ franz_icon_dir }}"
    state: directory
    mode: 0755

- name: Add application icon
  copy:
    src: icon.png
    dest: "{{ franz_icon_dir }}/franz.png"
    mode: 0644

- name: Create application shortcut
  template:
    src: franz.desktop.j2
    dest: "{{ franz_desktop_dir }}/franz.desktop"
    mode: 0644
